server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    # 注意，使用gateway，需要在被监听的服务引入 spring-boot-starter-actuator
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment-route  #路由的id，没有固定的规则，但是要求唯一，建议配合服务名
#          uri: http://127.0.0.1:8001        #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER    #匹配后提供服务的路由地址，使用lb，为了服务的负载均衡
          predicates:
            - Path=/payment/get/**              #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment-route  #路由的id，没有固定的规则，但是要求唯一，建议配合服务名
#          uri: http://127.0.0.1:8001        #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER    #匹配后提供服务的路由地址，使用lb，为了服务的负载均衡
          predicates:
            - Path=/payment/lb/**              #断言，路径相匹配的进行路由
#            - After=2021-05-28T14:33:55.696+08:00[Asia/Shanghai]  # 在时间之后，网关起效 （时间串，从 ZonedDateTime  获取）
#            - Cookie=userName,xing        #请求待cookie，key 和 value{使用curl请求，在cmd中 （#curl http://127.0.0.1:9527/payment/lb/getDiscovery --cookie "userName=xing"）}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service