server:
  port: 8001
spring:
  application:
    name: cloud-payment-server
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    username: wind56-test
#    password: FengCe56
#    url: jdbc:mysql://101.132.147.155:50110/wind56test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 20
#      auto-commit: false
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloudalibaba #?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xing.entity
#注册到eureka服务端
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进Eurekaserver默认为true。
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/ #单机版
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8001 #服务名称修改（也就是将IP地址，换成可读性高的名字）
    prefer-ip-address: true #访问路径可以显示ip地址
    #心跳检测与续约时间
    #开发时设置小些，保证服务关闭后注册中心能及时剔除服务
    #eureka客户端向服务端发送心跳包的间隔时间，单位为妙（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳等待时间上限，单位为妙（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2
