server:
  port: 8006
spring:
  application:
    name: cloud-prodiver-payment
  cloud:
    consul:
      host: 116.62.50.222
      port: 8500
      discovery:
        service-name: ${spring.application.name}