server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  #从本地读取配置文件
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
  #从本地读取配置文件，这里必须设置
  profiles:
    active: native

  #rabbitmq相关配置<--------------------------
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


# 从外部配置获取配置信息
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xing-only/springcloud_alibaba.git #git@github.com:xing-only/springcloud_alibaba.git
#          search-paths:
#            - parentobj/cloud-config-server3344/src/main/resources/
#      label: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点<--------------------------
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'