server:
  port: 80
spring:
  application:
    name: cloud-feign-order80
eureka:
  client:
    fetch-registry: true #从eurekaserver服务中，抓取已有的注册信息，默认true
    register-with-eureka: true #是否注册到eureka 服务中，默认true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  ReadTimeout: 5000 #指建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间

#开启feign的hystrix支持,默认是false
feign:
  hystrix:
    enabled: true