server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 116.62.50.222
      port: 8500
      discovery:
        service-name: ${spring.application.name}